### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by ryanseghers** [WiringPi/WiringPi-Node#67]
I'm trying to get going with WiringPi on my Raspberry Pi 2. I have a build failure. Am I doing something wrong?

Here is the failure:
pi@raspberrypi ~/src/testNpmWiringPi $ npm install wiring-pi

> wiring-pi@2.2.1 install /home/pi/src/testNpmWiringPi/node_modules/wiring-pi
> /bin/bash ./install.sh

Cloning libWiringPi ... done.
patching file ./wiringpi/devLib/Makefile
Hunk #1 succeeded at 24 with fuzz 1 (offset -2 lines).
Hunk #2 succeeded at 32 with fuzz 2 (offset -2 lines).
patching file ./wiringpi/gpio/Makefile
Making libWiringPi ... done.
Making devLib ...done.
Unistalling gpio utility ... done.
Making gpio utility ... done.
Installing gpio utility ... done.
Making wiring-pi ... gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/pi/src/testNpmWiringPi/node_modules/wiring-pi/build'
  CXX(target) Release/obj.target/wiringPi/src/addon.o
In file included from ../src/addon.h:4:0,
                 from ../src/addon.cc:1:
/home/pi/.node-gyp/7.5.0/include/node/v8.h:346:1: error: expected unqualified-id before ‘using’
/home/pi/.node-gyp/7.5.0/include/node/v8.h:849:1: error: expected unqualified-id before ‘using’
/home/pi/.node-gyp/7.5.0/include/node/v8.h:5578:35: error: ‘virtual v8::EmbedderHeapTracer::~EmbedderHeapTracer()’ declared virtual cannot be defaulted in the class body
In file included from ../src/addon.cc:1:0:
../src/addon.h:12:24: error: ‘Handle’ is not a member of ‘v8’
../src/addon.h:12:44: error: expected primary-expression before ‘>’ token
[snip] (a lot more errors in this file)
wiringPi.target.mk:135: recipe for target 'Release/obj.target/wiringPi/src/addon.o' failed
make: *** [Release/obj.target/wiringPi/src/addon.o] Error 1
make: Leaving directory '/home/pi/src/testNpmWiringPi/node_modules/wiring-pi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.1.19-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v7.5.0/bin/node" "/home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/src/testNpmWiringPi/node_modules/wiring-pi
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

**Comment by ryanseghers** [comment]
This failure happened on the "wheezy" build of rasbian. I upgraded to 4.4 "jessie" and now it's working.
